---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: data
  namespace: cnb-nodejs
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 1Gi
