---
apiVersion: v1
kind: Service
metadata:
  name: app
  namespace: cnb-nodejs
spec:
  type: LoadBalancer
  ports:
    - port: 80
      protocol: TCP
      targetPort: 8080
  selector:
    app: cnb-nodejs
