apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  namespace: cnb-nodejs
  name: app
spec:
  rules:
  - host: nodejs.withtanzu.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: app
            port:
              number: 80
